[KeyACTIVATE]
key = k
type = cycle
$active = 0,1

[Constants]
global $active = 1
;EDIT THIS
global $xyz_scale = 0.5
global $x_rotate_speed_multiplier = 0.0
global $y_rotate_speed_multiplier = 1.0
global $z_rotate_speed_multiplier = 0.0
global $x_offset = 0
global $y_offset = 0
global $z_offset = 0


global $time
global $speed_multiplier = 3.0

[Present]
$time = (time * $speed_multiplier) % 6.5

[CustomShader123]
x54 = $x_offset
y54 = $y_offset
z54 = $z_offset
x55 = $time * $x_rotate_speed_multiplier
y55 = $time * $y_rotate_speed_multiplier
z55 = $time * $z_rotate_speed_multiplier
x56 = $xyz_scale
cs = 1f543271de52fe8d-cs.hlsl
dispatch = THREAD_GROUP_COUNT_X,1,1


[ShaderOverride123]
hash = 1f543271de52fe8d
if $active
    if draw_type == 8
    handling = skip
    run = CustomShader123
    endif
endif 

[ResourceU0]
type = RWBuffer
stride = 16
