[TextureOverrideJeanPosition]
hash = 191af650
vb0 = ResourceJeanPosition

[TextureOverrideJeanBlend]
hash = 3cb8153c
vb1 = ResourceJeanBlend
run = CustomShaderCustomBlend

[TextureOverrideJeanTexcoord]
hash = 1722136c
vb1 = ResourceJeanTexcoord

[TextureOverrideJeanVertexLimitRaise]
hash = 6fe07e12

[TextureOverrideJeanIB]
hash = 115737ff
handling = skip
drawindexed = auto

[TextureOverrideJeanHead]
hash = 115737ff
match_first_index = 0
ib = ResourceJeanHeadIB
ps-t0 = ResourceJeanHeadDiffuse
ps-t1 = ResourceJeanHeadLightMap
ps-t2 = ResourceJeanHeadShadowRamp

[TextureOverrideJeanBody]
hash = 115737ff
match_first_index = 7779
ib = ResourceJeanBodyIB
ps-t0 = ResourceJeanBodyDiffuse
ps-t1 = ResourceJeanBodyLightMap
ps-t2 = ResourceJeanBodyMetalMap
ps-t3 = ResourceJeanBodyShadowRamp

[TextureOverrideJeanFaceHeadDiffuse]
hash = c2d1a57e
ps-t0 = ResourceJeanFaceHeadDiffuse

[CustomShaderCustomBlend]
vs = Bone.hlsl
ResourceTempT1 = copy vs-t1
vs-t1 = ResourceData
handling = skip
draw = 17251,0
post vs-t1 = ResourceTempT1

[ResourceJeanPosition]
type = Buffer
stride = 40
filename = JeanPosition.buf

[ResourceJeanBlend]
type = Buffer
stride = 32
filename = JeanBlend.buf

[ResourceJeanTexcoord]
type = Buffer
stride = 12
filename = JeanTexcoord.buf

[ResourceJeanHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = JeanHead.ib

[ResourceJeanBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = JeanBody.ib

[ResourceJeanHeadDiffuse]
filename = CentaurJeanBBodyDiffuse.dds

[ResourceJeanHeadLightMap]
filename = CentaurJeanBBodyLightMap.dds

[ResourceJeanHeadShadowRamp]
filename = JeanHeadShadowRamp.jpg

[ResourceJeanBodyDiffuse]
filename = CentaurJeanBBodyDiffuse.dds

[ResourceJeanBodyLightMap]
filename = CentaurJeanBBodyLightMap.dds

[ResourceJeanBodyMetalMap]
filename = JeanBodyMetalMap.dds

[ResourceJeanBodyShadowRamp]
filename = JeanBodyShadowRamp.jpg

[ResourceJeanFaceHeadDiffuse]
filename = JeanFaceHeadDiffuse.dds

[ResourceTempT1]

[ResourceData]
type = Buffer
format = R32G32B32A32_FLOAT
data = 0 0 0 0    0 0.65 0 0    0 0.65 -0.85 0    0 0 0 0    105 0 0 0
;      offset0    offset1    offset2    offset3    params (bonescount,0,0,0)