; Soldier0

; Constants -------------------------
[ResourceT0_0]
[ResourceT0_1]
[ResourceMergedSkeleton]
type = RWBuffer
format = R32G32B32A32_FLOAT
array = 1024

[Constants]
global $component0_vgo = 0
global $component0_vgc = 90
global $component1_vgo = 90
global $component1_vgc = 117

[CustomShaderWrite]
cs-t55 = copy vs-t0
cs-u6 = ResourceMergedSkeleton
cs = bone_merge.hlsl
dispatch = y0, 1, 1

; x0 = $component0_vgo
; y0 = $component0_vgc
; run = CustomShaderWrite
; vs-t0 = cs-u6

; x0 = $component1_vgo
; y0 = $component1_vgc
; run = CustomShaderWrite
; vs-t0 = cs-u6

; Overrides -------------------------

[TextureOverrideSoldier0HairBlend]
hash = d13ddfe1
handling = skip
vb2 = ResourceSoldier0HairBlend
if DRAW_TYPE == 1
	vb0 = ResourceSoldier0HairPosition
	x0 = $component0_vgo
	y0 = $component0_vgc
	run = CustomShaderWrite
	vs-t0 = cs-u6

	draw = 19234, 0
endif

[TextureOverrideSoldier0HairTexcoord]
hash = c6b7b3b2
vb1 = ResourceSoldier0HairTexcoord

[TextureOverrideSoldier0HairVertexLimitRaise]
hash = 9a4ae9c7
override_vertex_count = 19234
override_byte_stride = 40

[TextureOverrideSoldier0BodyBlend]
hash = d4ff3f35
handling = skip
vb2 = ResourceSoldier0BodyBlend
if DRAW_TYPE == 1
	vb0 = ResourceSoldier0BodyPosition
	x0 = $component1_vgo
	y0 = $component1_vgc
	run = CustomShaderWrite
	vs-t0 = cs-u6
	draw = 19234, 0
endif

[TextureOverrideSoldier0BodyTexcoord]
hash = 80d87313
vb1 = ResourceSoldier0BodyTexcoord

[TextureOverrideSoldier0BodyVertexLimitRaise]
hash = 36089968
override_vertex_count = 19234
override_byte_stride = 40

[TextureOverrideSoldier0HairIB]
hash = 217ec790
handling = skip

[TextureOverrideSoldier0HairB]
hash = 217ec790
match_first_index = 33762
ib = ResourceSoldier0HairBIB
Resource\ZZMI\Diffuse = ref ResourceSoldier0HairBDiffuse
Resource\ZZMI\NormalMap = ref ResourceSoldier0HairBNormalMap
Resource\ZZMI\LightMap = ref ResourceSoldier0HairBLightMap
Resource\ZZMI\MaterialMap = ref ResourceSoldier0HairBMaterialMap
run = CommandList\ZZMI\SetTextures
; aaa.001 (19234)
drawindexed = 70929, 0, 0

[TextureOverrideSoldier0BodyIB]
hash = 53d3f4e5
handling = skip

[TextureOverrideSoldier0BodyA]
hash = 53d3f4e5
match_first_index = 0
ib = ResourceSoldier0BodyAIB
Resource\ZZMI\Diffuse = ref ResourceSoldier0BodyADiffuse
Resource\ZZMI\NormalMap = ref ResourceSoldier0BodyANormalMap
Resource\ZZMI\LightMap = ref ResourceSoldier0BodyALightMap
Resource\ZZMI\MaterialMap = ref ResourceSoldier0BodyAMaterialMap
run = CommandList\ZZMI\SetTextures
; aaa (19234)
; drawindexed = 70929, 0, 0


; CommandList -----------------------


; Resources -------------------------

[ResourceSoldier0HairPosition]
type = Buffer
stride = 40
filename = Soldier0HairPosition.buf

[ResourceSoldier0HairBlend]
type = Buffer
stride = 32
filename = Soldier0HairBlend.buf

[ResourceSoldier0HairTexcoord]
type = Buffer
stride = 20
filename = Soldier0HairTexcoord.buf

[ResourceSoldier0HairAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Soldier0HairA.ib

[ResourceSoldier0HairBIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Soldier0HairB.ib

[ResourceSoldier0BodyPosition]
type = Buffer
stride = 40
filename = Soldier0BodyPosition.buf

[ResourceSoldier0BodyBlend]
type = Buffer
stride = 32
filename = Soldier0BodyBlend.buf

[ResourceSoldier0BodyTexcoord]
type = Buffer
stride = 24
filename = Soldier0BodyTexcoord.buf

[ResourceSoldier0BodyAIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Soldier0BodyA.ib

[ResourceSoldier0HairADiffuse]
filename = Soldier0HairADiffuse.dds

[ResourceSoldier0HairANormalMap]
filename = Soldier0HairANormalMap.dds

[ResourceSoldier0HairALightMap]
filename = Soldier0HairALightMap.dds

[ResourceSoldier0HairAMaterialMap]
filename = Soldier0HairAMaterialMap.dds

[ResourceSoldier0HairBDiffuse]
filename = Soldier0HairBDiffuse.dds

[ResourceSoldier0HairBNormalMap]
filename = Soldier0HairBNormalMap.dds

[ResourceSoldier0HairBLightMap]
filename = Soldier0HairBLightMap.dds

[ResourceSoldier0HairBMaterialMap]
filename = Soldier0HairBMaterialMap.dds

[ResourceSoldier0BodyADiffuse]
filename = Soldier0BodyADiffuse.dds

[ResourceSoldier0BodyANormalMap]
filename = Soldier0BodyANormalMap.dds

[ResourceSoldier0BodyALightMap]
filename = Soldier0BodyALightMap.dds

[ResourceSoldier0BodyAMaterialMap]
filename = Soldier0BodyAMaterialMap.dds


; .ini generated by XXMI (XX-Model-Importer) v1.5.8
; If you have any issues or find any bugs, please open a ticket at https://github.com/leotorrez/XXMI-Tools/issues
