import bpy
import os
import shutil
from pathlib import Path

def get_target_path(context):
    """Надежное получение пути экспорта (XXMI -> Custom)."""
    settings = context.scene.rzm.export_settings
    path = ""
    
    # 1. Пробуем взять путь из XXMI, если галочка включена
    if settings.use_xxmi_path:
        # Проверка hasattr защищает от краша, если XXMI удален
        if hasattr(context.scene, 'xxmi') and hasattr(context.scene.xxmi, 'destination_path'):
            path = context.scene.xxmi.destination_path

    # 2. Если путь пуст (XXMI нет или путь не задан), берем кастомный
    if not path:
        path = settings.custom_path
        
    # Превращаем // в полный путь
    return bpy.path.abspath(path) if path else None

def generate_readme(target_path, mod_name):
    """Генерация простого ReadMe.txt."""
    readme_path = os.path.join(target_path, "ReadMe.txt")
    
    content = f"""; ===========     ABOUT     =============
; "{mod_name}"
; Generated by RZMenu Constructor

; ===========   TERMS OF USE   ==========
; Redistribution or resale of this mod is not allowed
; without permission.
;
; ===========      CONTACT     ==========
; (Add your contact info here)
"""
    try:
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    except Exception as e:
        print(f"RZM ReadMe Error: {e}")
        return False

class RZM_OT_InitializeMod(bpy.types.Operator):
    """Копирует файлы Basic Pack и создает структуру мода."""
    bl_idname = "rzm.initialize_mod"
    bl_label = "Initialize Mod Files"
    bl_description = "Копирует скрипты и шейдеры из RZMenu Basic Pack в папку мода"
    
    def execute(self, context):
        settings = context.scene.rzm.export_settings
        target_path = get_target_path(context)
        
        # Проверки на дурака
        if not target_path:
            self.report({'ERROR'}, "Path not set! Check XXMI settings or Custom Path.")
            return {'CANCELLED'}
            
        if not os.path.exists(target_path):
            try:
                os.makedirs(target_path, exist_ok=True)
            except Exception as e:
                self.report({'ERROR'}, f"Cannot create folder: {e}")
                return {'CANCELLED'}
            
        # 1. Ищем папку basic_pack внутри аддона
        # operators/export_manager.py -> (parent) -> operators -> (parent) -> RZMenu -> basic_pack
        addon_dir = Path(__file__).parent.parent
        basic_pack_src = addon_dir / "basic_pack"
        
        if not basic_pack_src.exists():
            self.report({'ERROR'}, f"Critical: 'basic_pack' folder missing in addon! Path: {basic_pack_src}")
            return {'CANCELLED'}
            
        # 2. Копирование файлов
        copied_count = 0
        try:
            # Рекурсивный обход папки
            for root, dirs, files in os.walk(basic_pack_src):
                rel_path = Path(root).relative_to(basic_pack_src)
                target_dir = Path(target_path) / rel_path
                
                if not target_dir.exists():
                    target_dir.mkdir(parents=True, exist_ok=True)
                    
                for file in files:
                    src_file = Path(root) / file
                    dst_file = target_dir / file
                    
                    # Копируем если файла нет ИЛИ если разрешена перезапись
                    if not dst_file.exists() or settings.overwrite_scripts:
                        shutil.copy2(src_file, dst_file)
                        copied_count += 1
                        
        except Exception as e:
            self.report({'ERROR'}, f"Copy Failed: {e}")
            import traceback
            traceback.print_exc()
            return {'CANCELLED'}

        # 3. Создаем ReadMe
        generate_readme(target_path, settings.mod_name)
        
        self.report({'INFO'}, f"Success! Copied {copied_count} files to {os.path.basename(target_path)}.")
        
        # 4. Сразу обновляем атлас, чтобы все работало из коробки
        if hasattr(bpy.ops.rzm, 'export_atlas'):
            bpy.ops.rzm.export_atlas()
        
        return {'FINISHED'}

# Стандартная регистрация для оператора
classes_to_register = [
    RZM_OT_InitializeMod
]