#RZMenu/operators/export_manager.py
import bpy
import os
import shutil
from pathlib import Path

def get_target_path(context, is_full=False):
    """Reliably get export path based on game context (XXMI/EFMI/WWMI -> Custom)."""
    rzm = context.scene.rzm
    settings = rzm.export_settings
    game = rzm.game.selection
    path = ""
    
    # 1. Try to take the path from game tool settings if enabled
    if settings.use_game_path:
        # Hoyoverse (XXMI)
        if game in ['GenshinImpact', 'ZenlessZoneZero', 'HonkaiStarRail']:
            if hasattr(context.scene, 'xxmi') and hasattr(context.scene.xxmi, 'destination_path'):
                path = context.scene.xxmi.destination_path
        
        # Endfield (EFMI)
        elif game == 'ArknightsEndfield':
            if hasattr(context.scene, 'efmi_tools_settings'):
                path = context.scene.efmi_tools_settings.mod_output_folder

        # Wuthering Waves (WWMI)
        elif game == 'WutheringWaves':
            if hasattr(context.scene, 'wwmi_tools_settings'):
                path = context.scene.wwmi_tools_settings.mod_output_folder

    # 2. Fallback to custom path if still empty
    if not path:
        path = settings.custom_path
        
    if not path:
        return None
        
    # Convert // relative paths to absolute
    abs_path = bpy.path.abspath(path)
    
    # 3. Handle Full Export Redirection (Neighboring place)
    if is_full and settings.use_neighbor_export:
        p = Path(abs_path)
        # Append _RZM suffix to the folder name
        abs_path = str(p.parent / (p.name + "_RZM"))

    return abs_path

def generate_readme(context, target_path):
    """Generates a ReadMe.txt using the 3-part description system."""
    from .tier_ops import get_prefs
    rzm = context.scene.rzm
    meta = rzm.meta_data
    prefs = get_prefs(context)
    
    readme_path = os.path.join(target_path, "ReadMe.txt")
    
    # Dynamic Title: Character (Outfit)
    mod_title = f"{meta.character_name} ({meta.outfit_name})"
    
    # 3-Part Description
    pre = prefs.pre_description if prefs else ""
    lore = meta.description
    post = prefs.post_description if prefs else ""
    
    # Author from Global Prefs
    author = prefs.author_name if prefs else "UNKNOWN"

    content = f"""; ===========     ABOUT     =============
; "{mod_title}"
; Author: {author}
; Generated by RZMenu Constructor

{pre}

; ===========      LORE       ===========
{lore}

{post}

; ===========   TERMS OF USE   ==========
; Redistribution or resale of this mod is not allowed
; without permission.
"""
    try:
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    except Exception as e:
        print(f"RZM ReadMe Error: {e}")
        return False

class RZM_OT_InitializeMod(bpy.types.Operator):
    """Копирует файлы Basic Pack и создает структуру мода."""
    bl_idname = "rzm.initialize_mod"
    bl_label = "Initialize Mod Files"
    bl_description = "Копирует скрипты и шейдеры из RZMenu Basic Pack в папку мода"
    
    def execute(self, context):
        settings = context.scene.rzm.export_settings
        target_path = get_target_path(context)
        
        # Проверки на дурака
        if not target_path:
            self.report({'ERROR'}, "Path not set! Check XXMI settings or Custom Path.")
            return {'CANCELLED'}
            
        if not os.path.exists(target_path):
            try:
                os.makedirs(target_path, exist_ok=True)
            except Exception as e:
                self.report({'ERROR'}, f"Cannot create folder: {e}")
                return {'CANCELLED'}
            
        # 1. Ищем папку basic_pack внутри аддона
        # operators/export_manager.py -> (parent) -> operators -> (parent) -> RZMenu -> basic_pack
        addon_dir = Path(__file__).parent.parent
        basic_pack_src = addon_dir / "basic_pack"
        
        if not basic_pack_src.exists():
            self.report({'ERROR'}, f"Critical: 'basic_pack' folder missing in addon! Path: {basic_pack_src}")
            return {'CANCELLED'}
            
        # 2. Копирование файлов
        copied_count = 0
        try:
            # Рекурсивный обход папки
            for root, dirs, files in os.walk(basic_pack_src):
                rel_path = Path(root).relative_to(basic_pack_src)
                target_dir = Path(target_path) / rel_path
                
                if not target_dir.exists():
                    target_dir.mkdir(parents=True, exist_ok=True)
                    
                for file in files:
                    src_file = Path(root) / file
                    dst_file = target_dir / file
                    
                    # Копируем если файла нет ИЛИ если разрешена перезапись
                    if not dst_file.exists() or settings.overwrite_scripts:
                        shutil.copy2(src_file, dst_file)
                        copied_count += 1
                        
        except Exception as e:
            self.report({'ERROR'}, f"Copy Failed: {e}")
            import traceback
            traceback.print_exc()
            return {'CANCELLED'}

        # 3. Создаем ReadMe
        generate_readme(context, target_path)
        
        self.report({'INFO'}, f"Success! Copied {copied_count} files to {os.path.basename(target_path)}.")
        
        # 4. Сразу обновляем атлас, чтобы все работало из коробки
        if hasattr(bpy.ops.rzm, 'export_atlas'):
            bpy.ops.rzm.export_atlas()
        
        return {'FINISHED'}

# Стандартная регистрация для оператора
classes_to_register = [
    RZM_OT_InitializeMod
]